language: c

matrix:
  include:
    - os: linux
      arch:
        - amd64
        - arm64
      dist: xenial
      sudo: required
      compiler:
        - gcc
        - clang
      addons:
        apt:
          update: true
          sources:
            - deadsnakes
            - sourceline: 'ppa:beineri/opt-qt-5.12.3-xenial'
          packages:
            - build-essential
            - qt512base
            - qt512declarative
            - libgl1-mesa-dev
      install:
        - source /opt/qt512/bin/qt512-env.sh

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt5; fi

script:
  - qmake --version
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - qmake config+="release" ../lcsniff.pro
  - make -j
